
FROM alpine:3.18

# Update and install PHP 8.1 (and other needed packages)
RUN apk update && apk upgrade && apk add --no-cache \
    curl mariadb-client php81 php81-fpm php81-phar \
    php81-mysqli php81-curl php81-iconv php81-dom \
    php81-exif php81-gd php81-json php81-fileinfo \
    php81-mbstring php81-openssl php81-xml php81-zip \
    && rm -rf /var/cache/apk/*

# Create the 'nginx' user and group
RUN addgroup nginx && \
    adduser -D -S -G nginx nginx

RUN mkdir -p /var/www/html/wordpress

COPY ./conf/www.conf /etc/php81/php-fpm.d/

# downloading wp-cli executable
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/bin/wp

# Set the working directory
WORKDIR /var/www/html/wordpress

COPY ./tools/wp_setup.sh .

RUN chmod 755 wp_setup.sh

# Expose the port
EXPOSE 9000

# Run PHP-FPM
CMD ["sh", "wp_setup.sh"]